# app.py
# The web front end. Owns HTTP concerns only — it parses nothing and detects
# nothing itself. It hands text to LogParser/BruteForceDetector and turns the
# AnalysisResult into JSON, exactly like the CLI turns it into text.
#
#   pip install -r requirements.txt
#   python app.py            -> http://127.0.0.1:5000
#
# Every number this serves is computed at request time. Nothing is canned:
# the sample cards report the analysis of the file as it is on disk right now,
# the history panel reports what SQLite actually holds, and the capability
# panel reports which integrations are genuinely configured.

import json
import os
import queue
import time

from flask import Flask, Response, jsonify, render_template, request

from alerts import AlertDispatcher
from config import config
from detector import (BruteForceDetector, DEFAULT_THRESHOLD, DEFAULT_WINDOW,
                      COMPROMISE_WINDOW, MIN_FAILURES_FOR_COMPROMISE,
                      Finding, HIGH)
from enrich import Enricher
from report import build_report
from storage import Storage
from watcher import LiveWatcher

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_DIR = os.path.join(BASE_DIR, "static")


def asset_version():
    """Newest mtime across the static files, as a cache-busting stamp.

    WHY: browsers hold on to a previously fetched app.js hard enough that a
    changed file can go unnoticed across a server restart, and the page then
    runs old code against a new API — controls silently missing, handlers
    bound to elements that no longer exist. Appending this to the URL makes a
    changed file a different URL, so it cannot be served from cache.
    """
    newest = 0.0
    for name in os.listdir(STATIC_DIR):
        try:
            newest = max(newest, os.path.getmtime(os.path.join(STATIC_DIR, name)))
        except OSError:
            continue
    return str(int(newest))

# Guard rails on tuning values arriving from the browser. A window of a
# hundred years is not a useful question and a threshold of 0 alerts on
# everything, so both are clamped rather than trusted.
LIMITS = {
    "threshold": (1, 1000),
    "window": (1, 86400),
    "compromise_window": (1, 86400),
    "min_failures": (1, 100),
    "hours": (1, 168),
}

# Where the bundled sample logs came from. Stated in the UI and in every
# generated report, because the first question anyone sensible asks of a
# security finding is "what am I looking at?"
DATA_PROVENANCE = (
    "Synthetic sample data, written for demonstration. Generated by "
    "make_logs.py and generate_log.py from published descriptions of SSH "
    "attack patterns — not captured from any real host, and containing no "
    "real addresses. All addresses are from the RFC 5737 documentation "
    "ranges (192.0.2.x, 198.51.100.x, 203.0.113.x) or RFC 1918 private space."
)

# Only these files can be fetched by name. Serving an arbitrary path from a
# query parameter would let anyone read /etc/passwd through the sample viewer.
# The two headline files, kept in the project root because they are the first
# thing anybody is told to try. Listed first so the web app offers the same
# starting point the README does.
EXAMPLE_LOGS = [
    {"name": "EXAMPLE-1-attacks-present.log", "label": "Example 1 — a day under attack"},
    {"name": "EXAMPLE-2-no-attacks.log", "label": "Example 2 — a quiet day"},
]

SAMPLES = [
    {"name": "auth_sample.log", "label": "Attack + compromise"},
    {"name": "clean_sample.log", "label": "Clean traffic"},
    {"name": "evasion_sample.log", "label": "Evasion techniques"},
    {"name": "noisy_sample.log", "label": "Real-world noise"},
]

# The logs/ folder, discovered at request time rather than listed here, so
# adding a file to it is enough to make it appear.
LOGS_DIR = os.path.join(BASE_DIR, "logs")


def bundled_logs():
    """Every log under logs/, grouped by its folder."""
    found = []
    if not os.path.isdir(LOGS_DIR):
        return found
    for group in sorted(os.listdir(LOGS_DIR)):
        folder = os.path.join(LOGS_DIR, group)
        if not os.path.isdir(folder):
            continue
        for name in sorted(os.listdir(folder)):
            if name.endswith(".log"):
                found.append({"name": f"logs/{group}/{name}", "group": group,
                              "label": name[:-4].replace("-", " ")})
    return found


SAMPLE_NAMES = {s["name"] for s in SAMPLES + EXAMPLE_LOGS}

# A generated log is written here so the browser can re-analyse it without
# re-uploading. One slot, overwritten each time.
GENERATED_NAME = "generated.log"

app = Flask(__name__)
app.config["MAX_CONTENT_LENGTH"] = config.max_upload_bytes

storage = Storage(config.db_path) if config.persist else None
enricher = Enricher()
dispatcher = AlertDispatcher(storage=storage)
watcher = None                       # created on demand by /api/live/start


# ---- helpers -------------------------------------------------------------

def clamp(name, value, fallback):
    low, high = LIMITS[name]
    try:
        number = int(value)
    except (TypeError, ValueError):
        return fallback
    return max(low, min(high, number))


def sample_path(name):
    # Membership test against a set built from the filesystem, never a path
    # join on user input. "logs/attacks/x.log" is only served if that exact
    # string was produced by our own directory listing, so "../.." can never
    # match however it is encoded.
    if name in SAMPLE_NAMES:
        return os.path.join(BASE_DIR, name)
    if name == GENERATED_NAME:
        path = os.path.join(BASE_DIR, GENERATED_NAME)
        return path if os.path.exists(path) else None
    if name in {entry["name"] for entry in bundled_logs()}:
        return os.path.join(BASE_DIR, *name.split("/"))
    return None


def source_kind_for(name):
    """Which provenance note applies to this input."""
    if name == GENERATED_NAME:
        return "generated"
    if name in SAMPLE_NAMES or name.startswith("logs/"):
        return "sample"
    return "upload"


def read_sample(name):
    path = sample_path(name)
    if path is None:
        return None
    with open(path, errors="replace") as f:
        return f.read()


def allowlist_from(form):
    """Allowlist entries from the request, falling back to the environment."""
    raw = form.get("allowlist")
    if raw is None:
        return list(config.allowlist)
    if isinstance(raw, str):
        raw = raw.replace("\n", ",").split(",")
    return [str(entry).strip() for entry in raw if str(entry).strip()]


def detector_from(form):
    return BruteForceDetector(
        threshold=clamp("threshold", form.get("threshold"), DEFAULT_THRESHOLD),
        window=clamp("window", form.get("window"), DEFAULT_WINDOW),
        compromise_window=clamp("compromise_window",
                                form.get("compromise_window"),
                                COMPROMISE_WINDOW),
        min_failures=clamp("min_failures", form.get("min_failures"),
                           MIN_FAILURES_FOR_COMPROMISE),
        detect_compromise=str(form.get("detect_compromise", "true")).lower()
        not in ("false", "0", "off"),
        allowlist=allowlist_from(form),
    )


def build_payload(result, persist_mode=None, geo_lookup=False):
    """AnalysisResult -> the JSON the browser renders, with enrichment.

    geo_lookup=True additionally asks an online geolocation service where each
    routable attacking address is. That sends those addresses to a third
    party, so it is off unless the operator asks for it, and only routable
    addresses are ever sent.
    """
    payload = result.to_dict()
    enrichment = enricher.enrich_findings(result.findings)

    if geo_lookup:
        for key, record in enrichment.items():
            if not record.get("routable"):
                continue
            found = enricher.investigate(key, ["builtin", "maxmind", "online"])
            record.update(found["merged"])
            online = found["methods"].get("online", {})
            record["geo_source"] = "online" if online.get("ok") else ""
            if online.get("error"):
                record["geo_error"] = online["error"]

    for entry in payload["findings"]:
        record = enrichment.get(entry["key"])
        if record:
            entry["enrichment"] = record
            entry["location"] = Enricher.describe(record)
        if storage is not None:
            history = storage.history_for(entry["key"])
            # times_seen counts prior sightings, so subtract nothing yet —
            # this run has not been recorded at the point we read it.
            entry["times_seen"] = history["times_seen"] if history else 0

    for offender in payload["top_offenders"]:
        record = enricher.lookup(offender["ip"])
        offender["location"] = Enricher.describe(record)
        offender["kind"] = record.get("kind")

    if storage is not None and persist_mode:
        payload["run_id"] = storage.record_run(result, mode=persist_mode,
                                               enrichment=enrichment)
        payload["history"] = storage.summary()

    return payload


# ---- pages ---------------------------------------------------------------

@app.route("/")
def index():
    return render_template(
        "index.html",
        samples=SAMPLES,
        # Rendered into the page rather than fetched afterwards: the lookup
        # controls must be there even if a script fails to load.
        lookup_providers=enricher.providers(),
        asset_version=asset_version(),
        defaults={"threshold": config.threshold or DEFAULT_THRESHOLD,
                  "window": config.window or DEFAULT_WINDOW,
                  "compromise_window": COMPROMISE_WINDOW,
                  "min_failures": MIN_FAILURES_FOR_COMPROMISE})


@app.after_request
def no_stale_assets(response):
    # Belt and braces alongside the version stamp.
    if request.path.startswith("/static/"):
        response.headers["Cache-Control"] = "no-cache, must-revalidate"
    return response


# ---- capability reporting ------------------------------------------------

# What the detection is built from. Asked often enough — "which library does
# the detecting?" — that the honest answer belongs in the product: none. The
# sliding window, the pivots and the compromise correlation are implemented
# in this project, in plain Python, and can be read in an afternoon.
BACKEND = {
    "detection": [
        {"name": "Sliding window over grouped failures", "where": "detector.py",
         "detail": "Pure Python. No detection library, no rules engine, no "
                   "machine learning — the algorithm is ~40 lines and you can "
                   "read every branch of it."},
        {"name": "Log parsing", "where": "log_parser.py",
         "detail": "Plain string operations against a whitelist of sshd line "
                   "forms. Deliberately not regular expressions: a whitelist "
                   "is easier to audit and cannot backtrack."},
        {"name": "Address classification", "where": "enrich.py",
         "detail": "Python's built-in ipaddress module against the IANA "
                   "special-purpose registries."},
    ],
    "stdlib": [
        ("ipaddress", "CIDR maths for the subnet pivot and the allowlist"),
        ("sqlite3", "history, repeat offenders, alert records"),
        ("argparse", "the command line"),
        ("json", "machine-readable output and the API"),
        ("smtplib / email", "email alerts"),
        ("urllib", "webhook and Slack delivery, online lookups"),
        ("socket", "reverse DNS"),
        ("threading / queue", "the live watcher and its subscribers"),
        ("html", "escaping log content into the report"),
        ("unittest", "the test suite"),
    ],
    "third_party": [
        {"name": "Flask", "required": True, "used_for": "the web layer only",
         "note": "The CLI, the detector and the evaluation harness import "
                 "nothing outside the standard library."},
        {"name": "gunicorn", "required": False,
         "used_for": "serving in the Docker image", "note": ""},
        {"name": "geoip2 + MaxMind GeoLite2", "required": False,
         "used_for": "offline country and network-operator lookup",
         "note": "Optional. Without it, addresses are still classified from "
                 "the address itself and no location is invented."},
    ],
    "not_used": [
        "fail2ban — this reports, it does not block",
        "No regular-expression rules engine",
        "No machine learning model",
        "No external threat-intelligence feed",
        "No commercial SIEM",
    ],
}


@app.route("/api/backend")
def backend():
    return jsonify(BACKEND)


@app.route("/api/config")
def get_config():
    """What is actually wired up. The UI shows the gaps rather than hiding them."""
    return jsonify({
        "config": config.to_dict(),
        "alerting": dispatcher.status(),
        "enrichment": enricher.status,
        "persistence": storage is not None,
        "lookup_providers": enricher.providers(),
        "allowlist": config.allowlist,
        "provenance": DATA_PROVENANCE,
        "live": watcher.status() if watcher else {"state": "stopped",
                                                  "running": False},
        "defaults": {"threshold": DEFAULT_THRESHOLD, "window": DEFAULT_WINDOW},
    })


# ---- samples -------------------------------------------------------------

@app.route("/api/lookup", methods=["POST"])
def lookup():
    """Look one address up with the methods the operator explicitly chose.

    Nothing is sent off this machine unless "online" is among them.
    """
    form = request.get_json(silent=True) or {}
    ip_text = str(form.get("ip", "")).strip()
    if not ip_text:
        return jsonify({"error": "No address supplied."}), 400

    methods = form.get("methods") or ["builtin"]
    if isinstance(methods, str):
        methods = [methods]
    return jsonify(enricher.investigate(ip_text, methods))


@app.route("/api/lookup/providers")
def lookup_providers():
    return jsonify(enricher.providers())


@app.route("/api/report", methods=["POST"])
def report():
    """Build a standalone HTML report for one analysis."""
    form = request.get_json(silent=True) or {}
    sample = form.get("sample")

    if sample:
        text = read_sample(sample)
        if text is None:
            return jsonify({"error": f"unknown sample: {sample}"}), 404
        source = sample
    else:
        text = form.get("text", "")
        source = form.get("source") or "pasted input"

    if not text.strip():
        return jsonify({"error": "No log text supplied."}), 400

    result = detector_from(form).analyze_text(text, source=source)

    history = {}
    if storage is not None:
        for finding in result.findings:
            record = storage.history_for(finding.key)
            if record:
                history[finding.key] = record

    if str(form.get("geo_lookup", "false")).lower() in ("1", "true", "on"):
        for finding in result.findings:
            if finding.pivot == "ip":
                enricher.investigate(finding.key,
                                     ["builtin", "maxmind", "online"])

    html = build_report(result, source_kind=source_kind_for(sample or source),
                        enricher=enricher, history=history)
    filename = (os.path.basename(str(source)).replace(" ", "_") or "report")
    return Response(html, mimetype="text/html", headers={
        "Content-Disposition":
            f'attachment; filename="bfla-report-{filename}.html"',
    })


@app.route("/api/samples")
def list_samples():
    """Sample cards, with stats computed by analysing each file right now.

    Deliberately not a stored description. If a sample file changes, the card
    changes with it, and a card can never claim something the tool does not
    actually produce.
    """
    detector = BruteForceDetector(allowlist=config.allowlist)
    catalogue = ([dict(s, group="examples") for s in EXAMPLE_LOGS]
                 + [dict(s, group="quick") for s in SAMPLES]
                 + [{"name": GENERATED_NAME, "label": "Generated log",
                     "group": "generated"}]
                 + bundled_logs())

    out = []
    for sample in catalogue:
        path = sample_path(sample["name"])
        if path is None:
            continue
        result = detector.analyze_file(path)
        stats = result.to_dict()["stats"]
        out.append({
            "name": sample["name"],
            "label": sample["label"],
            "group": sample.get("group", "quick"),
            "lines": stats["events"] + stats["skipped"],
            "events": stats["events"],
            "skipped": stats["skipped"],
            "findings": stats["findings"],
            "high": stats["high"],
            "size_bytes": os.path.getsize(path),
        })
    return jsonify({"provenance": DATA_PROVENANCE, "samples": out})


@app.route("/api/samples/<name>")
def get_sample(name):
    text = read_sample(name)
    if text is None:
        return jsonify({"error": f"unknown sample: {name}"}), 404
    return jsonify({"name": name, "text": text})


# ---- generation ----------------------------------------------------------

@app.route("/api/generate", methods=["POST"])
def generate():
    """Build a fresh realistic log server-side, then hand it back.

    The generator plants attacks and reports what it planted, so the response
    carries ground truth the browser can score the detector against.
    """
    from generate_log import build

    form = request.get_json(silent=True) or {}
    hours = clamp("hours", form.get("hours"), 24)
    seed = form.get("seed")
    try:
        seed = int(seed) if seed not in (None, "") else None
    except (TypeError, ValueError):
        seed = None

    text, attacks = build(hours=hours, seed=seed)
    path = os.path.join(BASE_DIR, GENERATED_NAME)
    with open(path, "w") as f:
        f.write(text)

    return jsonify({
        "name": GENERATED_NAME,
        "text": text,
        "lines": text.count("\n"),
        "hours": hours,
        "seed": seed,
        "planted": [{"name": a["name"], "description": a["description"],
                     "keys": sorted(a["keys"])} for a in attacks],
    })


@app.route("/api/verify", methods=["POST"])
def verify():
    """Score the detector against a generated log's planted attacks."""
    from generate_log import build

    form = request.get_json(silent=True) or {}
    hours = clamp("hours", form.get("hours"), 24)
    try:
        seed = int(form.get("seed"))
    except (TypeError, ValueError):
        return jsonify({"error": "verify needs the seed the log was built with"}), 400

    text, attacks = build(hours=hours, seed=seed)
    detector = detector_from(form)
    result = detector.analyze_text(text, source=f"generated seed={seed}")
    hit_keys = {f.key for f in result.findings}

    legitimate = set()
    for attack in attacks:
        legitimate |= attack["keys"]

    scored = []
    caught = 0
    for attack in attacks:
        matched = sorted(hit_keys & attack["keys"])
        if matched:
            caught += 1
        scored.append({"name": attack["name"],
                       "description": attack["description"],
                       "found": bool(matched), "matched_on": matched})

    false_alarms = [f.to_dict() for f in result.findings
                    if f.key not in legitimate]
    total = len(attacks)
    recall = caught / total if total else 0.0
    precision = (caught / (caught + len(false_alarms))
                 if caught or false_alarms else 0.0)

    return jsonify({
        "threshold": detector.threshold, "window": detector.window,
        "planted": total, "caught": caught, "missed": total - caught,
        "false_alarms": false_alarms,
        "precision": round(precision, 3), "recall": round(recall, 3),
        "attacks": scored,
        "analysis": build_payload(result),
    })


# ---- analysis ------------------------------------------------------------

@app.route("/api/analyze", methods=["POST"])
def analyze():
    # Two ways in: a JSON body with pasted text, or a multipart file upload.
    if request.files.get("logfile"):
        upload = request.files["logfile"]
        source = upload.filename or "uploaded file"
        text = upload.read().decode("utf-8", errors="replace")
        form = request.form
    else:
        form = request.get_json(silent=True) or {}
        sample = form.get("sample")
        if sample:
            text = read_sample(sample)
            if text is None:
                return jsonify({"error": f"unknown sample: {sample}"}), 404
            source = sample
        else:
            text = form.get("text", "")
            source = "pasted input"

    if not text.strip():
        return jsonify({"error": "No log text supplied."}), 400

    geo = str(form.get("geo_lookup", "false")).lower() in ("1", "true", "on")
    result = detector_from(form).analyze_text(text, source=source)
    payload = build_payload(result, persist_mode="batch", geo_lookup=geo)
    payload["source_kind"] = source_kind_for(form.get("sample") or source)
    payload["provenance"] = (DATA_PROVENANCE
                             if payload["source_kind"] == "sample" else "")

    # Batch analysis alerts too, so a cron job driving /api/analyze behaves
    # the same as the live watcher.
    if str(form.get("alert", "false")).lower() in ("1", "true", "on"):
        payload["alerts"] = {
            f.key: [r.to_dict() for r in dispatcher.dispatch(
                f, {"source": source, "mode": "batch"})]
            for f in result.findings}

    return jsonify(payload)


# ---- history -------------------------------------------------------------

@app.route("/api/history")
def history():
    if storage is None:
        return jsonify({"enabled": False,
                        "reason": "persistence disabled (BFLA_PERSIST=false)"})
    return jsonify({
        "enabled": True,
        "summary": storage.summary(),
        "runs": storage.recent_runs(limit=15),
        "repeat_offenders": storage.repeat_offenders(limit=15),
    })


@app.route("/api/history/reset", methods=["POST"])
def history_reset():
    """Wipe the recorded history. Clearing should actually clear."""
    if storage is None:
        return jsonify({"error": "persistence disabled"}), 404
    removed = storage.reset()
    return jsonify({"cleared": True, "removed": removed,
                    "summary": storage.summary()})


@app.route("/api/history/<path:key>")
def history_for(key):
    if storage is None:
        return jsonify({"error": "persistence disabled"}), 404
    record = storage.history_for(key)
    if record is None:
        return jsonify({"error": f"never seen: {key}"}), 404
    return jsonify(record)


# ---- alerts --------------------------------------------------------------

@app.route("/api/alerts")
def alerts_status():
    return jsonify({
        "status": dispatcher.status(),
        "recent": storage.recent_alerts() if storage else [],
    })


@app.route("/api/alerts/test", methods=["POST"])
def alerts_test():
    """Send a clearly-labelled test through every configured channel."""
    if not dispatcher.ready_channels:
        return jsonify({
            "sent": False,
            "reason": "no channel configured",
            "channels": dispatcher.status()["channels"],
        }), 400

    probe = Finding("test", "ip", "203.0.113.1", HIGH,
                    "TEST ALERT — configuration check, not a real detection")
    results = [r.to_dict() for r in dispatcher.dispatch(
        probe, {"source": "configuration test", "mode": "test"},
        now=time.time() + dispatcher.cooldown + 1)]   # bypass cooldown
    return jsonify({"sent": any(r["ok"] for r in results), "results": results})


# ---- live monitoring -----------------------------------------------------

@app.route("/api/live/start", methods=["POST"])
def live_start():
    global watcher

    form = request.get_json(silent=True) or {}
    path = (form.get("path") or config.watch_path or "").strip()
    if not path:
        return jsonify({
            "error": "No log path to follow.",
            "hint": "Set BFLA_WATCH_PATH, or pass {\"path\": \"...\"}. "
                    "On Linux this is usually /var/log/auth.log.",
        }), 400

    if watcher and watcher.running:
        watcher.stop()

    watcher = LiveWatcher(
        path,
        detector=detector_from(form),
        retention_seconds=config.watch_retention_seconds,
        poll_seconds=config.watch_poll_seconds,
        storage=storage, dispatcher=dispatcher, enricher=enricher)
    watcher.start(from_end=bool(form.get("from_end", True)))
    return jsonify(watcher.status())


@app.route("/api/live/stop", methods=["POST"])
def live_stop():
    if watcher:
        watcher.stop()
    return jsonify(watcher.status() if watcher else {"state": "stopped",
                                                     "running": False})


@app.route("/api/live/status")
def live_status():
    if not watcher:
        return jsonify({"state": "stopped", "running": False,
                        "configured_path": config.watch_path})
    return jsonify(watcher.status())


@app.route("/api/live/snapshot")
def live_snapshot():
    if not watcher:
        return jsonify({"error": "not running"}), 404
    return jsonify(build_payload(watcher.snapshot()))


@app.route("/api/live/stream")
def live_stream():
    """Server-Sent Events: findings pushed to the browser as they happen."""
    if not watcher:
        return jsonify({"error": "not running"}), 404

    active = watcher

    def events():
        listener = active.subscribe()
        try:
            yield f"data: {json.dumps({'type': 'state', 'data': active.status()})}\n\n"
            while True:
                try:
                    message = listener.get(timeout=15)
                    yield f"data: {json.dumps(message)}\n\n"
                except queue.Empty:
                    # A comment frame keeps proxies from closing an idle
                    # connection, and tells the browser we are still here.
                    yield ": keepalive\n\n"
        finally:
            active.unsubscribe(listener)

    return Response(events(), mimetype="text/event-stream", headers={
        "Cache-Control": "no-cache",
        "X-Accel-Buffering": "no",
        "Connection": "keep-alive",
    })


@app.errorhandler(413)
def too_large(_):
    limit_mb = config.max_upload_bytes // (1024 * 1024)
    return jsonify({"error": f"Log file too large (limit {limit_mb} MB)."}), 413


if __name__ == "__main__":
    print(f" * Persistence : {config.db_path if storage else 'disabled'}")
    print(f" * Geo lookup  : {'ready' if enricher.geo_available else enricher.provider.error}")
    print(f" * Alerting    : {', '.join(c.name for c in dispatcher.ready_channels) or 'no channel configured'}")
    print(f" * Live watch  : {config.watch_path or 'no BFLA_WATCH_PATH set'}")
    app.run(debug=config.debug, port=config.port, threaded=True)
