# report.py
# ONE JOB: turn an AnalysisResult into a standalone HTML report.
#
# Standalone means exactly that: one file, no stylesheet, no script, no font
# and no image fetched from anywhere. It opens from a USB stick on a machine
# with no network, prints to PDF from any browser, and can be attached to a
# ticket without shipping a folder of assets alongside it.
#
# Every figure comes from the AnalysisResult. Nothing is hardcoded, and where
# a value is unknown the report says unknown rather than filling a gap.

import html
import os
from datetime import datetime

from enrich import Enricher

# The report states where its input came from. A reader who has never seen
# this tool should not have to guess whether they are looking at a real
# incident or a demonstration.
PROVENANCE = {
    "sample": ("Bundled sample log — synthetic data written for demonstration. "
               "Not captured from a real host."),
    "generated": ("Generated by generate_log.py — synthetic traffic shaped "
                  "from published descriptions of SSH attack patterns. "
                  "Not captured from a real host."),
    "upload": "Supplied by the operator.",
    "live": "Read from a log file being followed in real time.",
    "paste": "Pasted into the web interface by the operator.",
}

SEVERITY_NOTE = {
    "HIGH": ("A failure sequence from this source ended in a SUCCESSFUL login. "
             "Treat as a confirmed compromise until proven otherwise: the "
             "account is in someone else's hands."),
    "MEDIUM": ("Repeated authentication failures crossed the configured "
               "threshold. An attempt, not a confirmed breach."),
}

CSS = """
*,*::before,*::after{box-sizing:border-box}
body{margin:0;padding:0;font:14px/1.6 -apple-system,BlinkMacSystemFont,
  "Segoe UI",Roboto,Helvetica,Arial,sans-serif;color:#1b2430;background:#eef1f6}
.page{max-width:900px;margin:0 auto;padding:32px 28px 64px;background:#fff;
  min-height:100vh;box-shadow:0 0 0 1px #dde3ec}
h1{margin:0 0 4px;font-size:23px;letter-spacing:-.02em}
h2{margin:32px 0 12px;font-size:12px;text-transform:uppercase;
  letter-spacing:.09em;color:#5c6b7e;border-bottom:1px solid #e4e9f0;
  padding-bottom:7px}
h3{margin:20px 0 8px;font-size:14px}
p{margin:0 0 10px}
.sub{color:#5c6b7e;font-size:13px;margin:0}
code,.mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
  font-size:12.5px}
.masthead{display:flex;justify-content:space-between;align-items:flex-start;
  gap:20px;flex-wrap:wrap;border-bottom:2px solid #1b2430;padding-bottom:16px}
.verdict{margin:22px 0;padding:14px 16px;border-radius:8px;border:1px solid;
  font-size:14px}
.verdict.breach{background:#fdf0f0;border-color:#cf2222;color:#8c1616}
.verdict.attempts{background:#fdf6e8;border-color:#a86500;color:#7a4a00}
.verdict.clear{background:#eef8f0;border-color:#1a7f37;color:#12622a}
.verdict strong{display:block;font-size:15px;margin-bottom:3px}
.banner{margin:16px 0 0;padding:10px 13px;border-radius:7px;
  background:#f2f5fa;border:1px solid #dde3ec;color:#41506a;font-size:12.5px}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(118px,1fr));
  gap:10px;margin:16px 0}
.tile{border:1px solid #e4e9f0;border-radius:8px;padding:11px 13px;
  background:#fafbfd}
.tile .n{font-size:22px;font-weight:650;letter-spacing:-.02em}
.tile .l{font-size:10.5px;text-transform:uppercase;letter-spacing:.06em;
  color:#5c6b7e;margin-top:2px}
.tile.bad .n{color:#cf2222}.tile.warn .n{color:#a86500}.tile.ok .n{color:#1a7f37}
table{width:100%;border-collapse:collapse;font-size:13px;margin:10px 0}
th{text-align:left;font-size:10.5px;text-transform:uppercase;
  letter-spacing:.06em;color:#5c6b7e;border-bottom:1px solid #dde3ec;
  padding:7px 9px 7px 0;font-weight:600}
td{padding:9px 9px 9px 0;border-bottom:1px solid #eef1f6;vertical-align:top}
tr:last-child td{border-bottom:none}
.tag{display:inline-block;padding:2px 7px;border-radius:4px;font-size:10.5px;
  font-weight:700;letter-spacing:.04em}
.tag.HIGH{background:#fdecec;color:#cf2222;border:1px solid #cf2222}
.tag.MEDIUM{background:#fdf4e6;color:#a86500;border:1px solid #a86500}
.tag.pivot{background:#f2f5fa;color:#41506a;border:1px solid #dde3ec;
  font-weight:600}
.chart{display:flex;align-items:flex-end;gap:2px;height:110px;margin:12px 0 4px;
  border-bottom:1px solid #dde3ec;padding-bottom:1px}
.chart .b{flex:1;background:#2563eb;min-height:2px;border-radius:2px 2px 0 0}
.chart .b.hot{background:#cf2222}
.axis{display:flex;justify-content:space-between;font-size:11px;color:#5c6b7e}
.bar{display:grid;grid-template-columns:150px 1fr 42px;gap:10px;
  align-items:center;margin-bottom:7px}
.bar .track{background:#eef1f6;border-radius:4px;height:9px;overflow:hidden}
.bar .fill{height:100%;background:#2563eb;border-radius:4px}
.bar.flagged .fill{background:#cf2222}
.bar .n{text-align:right;color:#5c6b7e}
.note{color:#5c6b7e;font-size:12.5px;margin:6px 0 0}
ul{margin:8px 0;padding-left:20px}li{margin-bottom:5px}
footer{margin-top:40px;padding-top:14px;border-top:1px solid #e4e9f0;
  color:#5c6b7e;font-size:12px}
@media print{
  body{background:#fff}
  .page{box-shadow:none;max-width:none;padding:0}
  h2{break-after:avoid}tr{break-inside:avoid}.verdict{break-inside:avoid}
}
"""


def esc(value):
    return html.escape(str(value if value is not None else ""))


class ReportBuilder:
    """Builds one self-contained HTML report from an AnalysisResult."""

    def __init__(self, result, source_kind="upload", generated_at=None,
                 enricher=None, history=None, tool_version="1.0"):
        self.result = result
        self.source_kind = source_kind
        self.generated_at = generated_at or datetime.now()
        self.enricher = enricher or Enricher()
        self.history = history or {}
        self.tool_version = tool_version

    # ---- narrative -------------------------------------------------

    def verdict(self):
        """One sentence a manager can act on, and the class of the box."""
        high = self.result.high_findings
        findings = self.result.findings
        if high:
            keys = ", ".join(sorted({f.key for f in high}))
            return ("breach", "Confirmed compromise",
                    f"{len(high)} source(s) authenticated successfully after "
                    f"repeated failures: {keys}. Treat the affected accounts "
                    f"as compromised — rotate credentials and review what was "
                    f"done in those sessions.")
        if findings:
            return ("attempts", "Attack attempts, no confirmed breach",
                    f"{len(findings)} finding(s) crossed the threshold of "
                    f"{self.result.threshold} failures in "
                    f"{self.result.window}s. Nothing in this log shows a "
                    f"successful login following those failures.")
        return ("clear", "No threats detected",
                f"Nothing in this log crossed {self.result.threshold} failures "
                f"within {self.result.window}s, and no failure sequence ended "
                f"in a successful login.")

    # ---- sections ---------------------------------------------------

    def masthead(self):
        stamp = self.generated_at.strftime("%d %B %Y at %H:%M")
        return f"""
        <div class="masthead">
          <div>
            <h1>SSH Brute Force Analysis</h1>
            <p class="sub">{esc(os.path.basename(str(self.result.source)))}</p>
          </div>
          <div class="sub" style="text-align:right">
            <div>{esc(stamp)}</div>
            <div class="mono">threshold {self.result.threshold} /
              {self.result.window}s</div>
          </div>
        </div>"""

    def provenance(self):
        note = PROVENANCE.get(self.source_kind, PROVENANCE["upload"])
        return f"""<div class="banner"><strong>Data source.</strong>
          {esc(note)}</div>"""

    def summary(self):
        stats = self.result.to_dict()["stats"]
        tiles = [
            ("Events parsed", stats["events"], ""),
            ("Failures", stats["failures"], ""),
            ("Successes", stats["successes"], ""),
            ("Unique sources", stats["unique_ips"], ""),
            ("Lines skipped", stats["skipped"], ""),
            ("Findings", stats["findings"], "warn" if stats["findings"] else "ok"),
            ("High severity", stats["high"], "bad" if stats["high"] else "ok"),
        ]
        cells = "".join(
            f'<div class="tile {cls}"><div class="n">{n}</div>'
            f'<div class="l">{esc(label)}</div></div>'
            for label, n, cls in tiles)
        return f'<h2>Summary</h2><div class="grid">{cells}</div>'

    def findings_table(self):
        if not self.result.findings:
            return ("<h2>Findings</h2><p>None. Every source in this log stayed "
                    "below the configured threshold.</p>")

        rows = []
        for f in self.result.findings:
            record = (self.enricher.lookup(f.key) if f.pivot == "ip" else {})
            where = Enricher.describe(record) if record else "—"
            seen = self.history.get(f.key, {}).get("times_seen", 0)
            history = (f"seen in {seen} previous analyses" if seen
                       else "first time seen")
            rows.append(f"""
              <tr>
                <td><span class="tag {esc(f.severity)}">{esc(f.severity)}</span></td>
                <td><span class="tag pivot">{esc(f.pivot)}</span></td>
                <td class="mono"><strong>{esc(f.key)}</strong><br>
                    <span class="note">{esc(where)}</span></td>
                <td>{esc(f.detail)}<br>
                    <span class="note">{esc(history)}</span></td>
              </tr>""")

        notes = "".join(
            f"<li><strong>{esc(sev)}</strong> — {esc(note)}</li>"
            for sev, note in SEVERITY_NOTE.items()
            if any(f.severity == sev for f in self.result.findings))

        return f"""<h2>Findings</h2>
          <table>
            <thead><tr><th>Severity</th><th>Grouped by</th>
              <th>Source</th><th>Evidence</th></tr></thead>
            <tbody>{''.join(rows)}</tbody>
          </table>
          <h3>What these mean</h3><ul>{notes}</ul>"""

    def suppressed_section(self):
        if not self.result.suppressed:
            return ""
        rows = "".join(
            f'<tr><td class="mono">{esc(f.key)}</td>'
            f'<td><span class="tag pivot">{esc(f.pivot)}</span></td>'
            f'<td>{esc(f.detail)}</td></tr>'
            for f in self.result.suppressed)
        entries = ", ".join(self.result.allowlist.raw) if self.result.allowlist else ""
        return f"""<h2>Suppressed by allowlist</h2>
          <p class="note">These crossed the threshold but were withheld because
            the operator listed their source as trusted
            (<span class="mono">{esc(entries)}</span>). Shown so nothing is
            hidden without a record.</p>
          <table><thead><tr><th>Source</th><th>Grouped by</th>
            <th>Evidence</th></tr></thead><tbody>{rows}</tbody></table>"""

    def timeline_section(self):
        buckets = self.result.timeline()
        if not buckets:
            return ""
        peak = max((b["failures"] for b in buckets), default=1) or 1
        bars = "".join(
            f'<div class="b{" hot" if b["failures"] >= peak * .75 and b["failures"] else ""}"'
            f' style="height:{max(b["failures"] / peak * 100, 2) if b["failures"] else 0}%"'
            f' title="{esc(b["label"])}: {b["failures"]}"></div>'
            for b in buckets)
        labelled = [b["label"] for b in buckets if b["label"]]
        first = labelled[0] if labelled else ""
        last = labelled[-1] if labelled else ""
        return f"""<h2>Failed attempts over time</h2>
          <div class="chart">{bars}</div>
          <div class="axis"><span class="mono">{esc(first)}</span>
            <span class="note">peak {peak} in one bucket</span>
            <span class="mono">{esc(last)}</span></div>"""

    def sources_section(self):
        offenders = self.result.top_offenders(limit=10)
        if not offenders:
            return ""
        flagged = {f.key for f in self.result.findings}
        peak = max((o["failures"] for o in offenders), default=1) or 1
        rows = []
        for o in offenders:
            record = self.enricher.lookup(o["ip"])
            rows.append(f"""
              <div class="bar {'flagged' if o['ip'] in flagged else ''}">
                <span class="mono" title="{esc(Enricher.describe(record))}">{esc(o['ip'])}</span>
                <span class="track"><span class="fill"
                  style="width:{o['failures'] / peak * 100:.1f}%"></span></span>
                <span class="n mono">{o['failures']}</span>
              </div>""")
        return (f"<h2>Busiest sources</h2>{''.join(rows)}"
                f'<p class="note">Red bars produced a finding. '
                f'Grey bars stayed below the threshold.</p>')

    def method_section(self):
        allow = (", ".join(self.result.allowlist.raw)
                 if self.result.allowlist and self.result.allowlist.raw
                 else "none")
        return f"""<h2>How this was produced</h2>
          <p>Each line was parsed into a structured event. Lines that are not
             authentication attempts were discarded rather than counted, and an
             rsyslog <span class="mono">message repeated N times</span> summary
             was expanded back into N attempts.</p>
          <p>Failures were then grouped four ways and checked against a sliding
             window of <strong>{self.result.threshold} failures within
             {self.result.window} seconds</strong>:</p>
          <ul>
            <li><strong>By source address</strong> — a single machine guessing.</li>
            <li><strong>By username</strong> — password spraying, or many
                machines against one account.</li>
            <li><strong>By /24 subnet</strong> — a botnet whose individual
                addresses each stay under the threshold.</li>
            <li><strong>Compromise correlation</strong> — failures that ended in
                a successful login. This one does not depend on the threshold
                at all, which is why it still fires when everything else is
                tuned too high.</li>
          </ul>
          <p class="note">Allowlisted sources: <span class="mono">{esc(allow)}</span>.
             Geo lookup: {"enabled" if self.enricher.geo_available else
             "not configured — addresses are classified from the address itself, "
             "and no location is invented."}</p>"""

    def limits_section(self):
        return """<h2>Limitations of this analysis</h2>
          <ul>
            <li>Syslog records no year, so a log spanning 31 December to
                1 January produces a negative interval and the attack is missed.</li>
            <li>Day-of-year arithmetic assumes a non-leap year: 29 February and
                1 March collapse to the same day.</li>
            <li>An rsyslog-collapsed line becomes N events sharing one
                timestamp, because the log does not record when the intermediate
                attempts happened. The burst therefore appears tighter than it
                was.</li>
            <li>Subnet grouping is IPv4 only. IPv6 addresses are reported
                individually.</li>
            <li>A threshold catches what crosses it. An attacker who stays one
                attempt below, forever, is invisible to the burst checks —
                only the compromise correlation would catch them, and only if
                they eventually succeed.</li>
          </ul>"""

    # ---- assembly ---------------------------------------------------

    def build(self):
        kind, headline, detail = self.verdict()
        title = f"SSH Brute Force Report — {os.path.basename(str(self.result.source))}"
        return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(title)}</title><style>{CSS}</style></head>
<body><div class="page">
{self.masthead()}
{self.provenance()}
<div class="verdict {kind}"><strong>{esc(headline)}</strong>{esc(detail)}</div>
{self.summary()}
{self.findings_table()}
{self.suppressed_section()}
{self.timeline_section()}
{self.sources_section()}
{self.method_section()}
{self.limits_section()}
<footer>Generated by Brute Force Log Analyzer v{esc(self.tool_version)} on
{esc(self.generated_at.strftime('%d %B %Y at %H:%M:%S'))}.
This file is self-contained — no network access is required to view it.</footer>
</div></body></html>"""


def build_report(result, **kwargs):
    return ReportBuilder(result, **kwargs).build()
